Update allure_report.yml

diff --git a/.github/workflows/allure_report.yml b/.github/workflows/allure_report.yml
--- a/.github/workflows/allure_report.yml
+++ b/.github/workflows/allure_report.yml
@@ -11,7 +11,6 @@ permissions:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
@@ -28,7 +27,7 @@ jobs:
 
     - name: Run tests and generate Allure results
       run: |
-        pytest -v --alluredir=./allure-results
+        pytest -v --alluredir=./allure-results || true  # Continue even if tests fail
 
     - name: Upload Allure results
       uses: actions/upload-artifact@v2
@@ -37,6 +36,7 @@ jobs:
         path: ./allure-results
 
   report:
+    needs: build
     runs-on: ubuntu-latest
 
     steps:
@@ -58,8 +58,8 @@ jobs:
     - name: Generate Allure report
       run: allure generate --clean allure-results -o allure-report
 
-    - name: Upload Allure report
-      uses: actions/upload-artifact@v2
-      with:
-        name: allure-report
-        path: ./allure-report
+    # - name: Upload Allure report
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     name: allure-report
+    #     path: ./allure-report
